### ISSUE TITLE
The clock shows a strange time

### ISSUE THREAD

**Issue by eqasxar** [nov30th/s1-mini-computer-tft-screen-release#3]
thanks for the good work. I have a few questions. The clock shows a strange time. I don't even understand what part of the world time it is. Bios is timed correctly, Proxmox too. Another question is how to change the background image. Your picture is too variegated, the information is difficult to see, it could be e.g. gray, or the possibility of changing according to the design itself.

**Comment by eqasxar** [comment]
Why is this red note displayed? What needs to be fixed? I wrote the IP address in internal linux.
![IMG_20240330_014936](https://github.com/nov30th/s1-mini-computer-tft-screen-release/assets/78238091/200d3a44-6a0b-4fa3-861c-5c5a2b532169)

**Comment by nov30th** [comment]
- you need to see the console logs, red error is from screen itselfs once there is no data to the screen in 2 seconds, the process of this program was exit I think.
- the time after power off might be incorrect which I haven't fully tested because my pc is alreays power on.
- the image can not be changed as it's during the pve version without open source but I will be open source later once I have time to continue coding this on my free time, might begins end of April.

**Comment by zencooler** [comment]
@nov30th thx for your great work on this! I also use your piece of software for this display. **Thanks in advance** for changing this background picture and check this time issue (I also have time issue each time after reboot - BIOS time is OK, linux time and time zone is OK, but displayed time is different (even minutes are different than on hardware clock).

**Comment by nov30th** [comment]
updates to this project will be indefinitely delayed.
